### ISSUE TITLE
Error: No available formula for zlib 

### ISSUE THREAD

**Issue by SocalNick** [mattheath/puppet-php#21] opened 2013-04-01 20:46 UTC
This was working fine last week, but just started emitting this error.

Error: No available formula for zlib 
Error: Could not set 'present' on ensure: undefined method `strip' for nil:NilClass at 76:/opt/boxen/repo/shared/php/manifests/init.pp
Error: Could not set 'present' on ensure: undefined method`strip' for nil:NilClass at 76:/opt/boxen/repo/shared/php/manifests/init.pp
Wrapped exception:
undefined method `strip' for nil:NilClass
Error: /Stage[main]/Php/Package[homebrew/dupes/zlib]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method`strip' for nil:NilClass at 76:/opt/boxen/repo/shared/php/manifests/init.pp

After this error, everything else to do with PHP says Skipping because of failed dependencies.

Homebrew says zlib is installed:
$ brew info zlib
zlib: stable 1.2.7
http://www.zlib.net/

This formula is keg-only.
Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

/opt/boxen/homebrew/Cellar/zlib/1.2.7 (9 files, 384K)
  Built from source
https://github.com/homebrew/homebrew-dupes/commits/master/zlib.rb
==> Options
--universal
    Build a universal binary

**Comment by SocalNick** [comment] 2013-04-01 21:41
Also:

``` console
$ brew tap homebrew/dupes
Error: Already tapped!
```

**Comment by mattheath** [comment] 2013-04-03 00:24
I'm also experiencing the same problem. At a guess it's an upstream homebrew change, but should be able to dig into it in the next couple of days.

**Comment by awirick** [comment] 2013-04-03 13:52
Agreed that it looks like an upstream change. just got some newly wiped machines and saw this today for the first time. Wasn't happening as of 5/6 days ago.

Thanks for your work so far @mattheath!

**Comment by mattheath** [comment] 2013-04-08 22:29
Partially fixed in `0.5.1`. This installs a custom zlib brew as `zlibphp` which the php module uses. This seems to be the only solution for the moment as it appears even creating a separate module ([mattheath/puppet-zlib](https://github.com/mattheath/puppet-zlib)) doesn't resolve this - boxen's version of homebrew currently won't import a formula called `zlib`.

Unfortunately previously installed versions of PHP will need to be removed  as they were compiled with `/opt/boxen/homebrew/opt/zlib` as the path, which is now `/opt/boxen/homebrew/opt/zlibphp`. Removing the `/opt/boxen/phpenv/versions/` then running Boxen with the updated module will recompile all of the PHP versions specified.

Fresh installs however will work!

**Comment by awirick** [comment] 2013-04-08 22:37
confirmed working for me with fresh install as of 0.5.1b1. Thanks!

**Comment by mattheath** [comment] 2013-04-08 22:40
Awesome, thanks @awirick. You might want to retag with the final `0.5.1` tag which is actually the latest one, sorry for any confusion!

**Comment by mattheath** [comment] 2013-04-13 09:23
Going to close this, please reopen if there are any issues.

**Closed as completed** 2013-04-13 09:23 UTC
