### ISSUE TITLE
cloning a private non-github repo

### ISSUE THREAD

**Issue by xavierfuentes** [mattheath/puppet-php#23] opened 2013-04-18 23:30 UTC
Sorry if i'm saying something stupid, but i really can't find how to clone a, for example, bitbucket repo where my php project is... is it possible? thanks in advance.

**Comment by mattheath** [comment] 2013-04-19 23:57
@xavifuefer the repository type which is used does allow you to specify a full url to a remote repository. For a Bitbucket repository you'll need the full https URL as short urls (as given in the example) are only supported for github repositories.

The source parameter on the `php::project` type is passed straight through to the repository puppet type, so you should be able to change the source parameter in this to a full url:

``` puppet
php::project { 'ohhai':
  source        => 'https://mattheath@bitbucket.org/mattheath/ohhai.git',
  elasticsearch => true,
  mysql         => true,
  nginx         => 'php/nginx/nginx.conf.erb',
  redis         => true,
  php           => '5.3.23',
}
```

I'm not sure specifically with bitbucket if the username can be omitted, i would hope so!

**Comment by xavierfuentes** [comment] 2013-04-20 00:39
did you tried with a private one? Boxen somehow should ask you for the repo password, shouldn't it? if I try just putting the bitbucket source, throws an error like "could not read Password for 'https://...': Device not configured"

**Comment by mattheath** [comment] 2013-04-20 09:28
Yes this was with a private repository - I tried with two different ones - and I didn't have to enter my password. However, in order to push code up to Bitbucket I had to enter my password a single time (for a _different_ repository) which was likely then cached in Boxen's git credential helper.

Can you try using the `repository` type to confirm if the behaviour is caused by this:

``` puppet
repository { "${boxen::config::srcdir}/somename":
  source => "bitbucket url",
}
```

I'd suggest filing an issue on [boxen/puppet-repository](https://github.com/boxen/puppet-repository) if you're still having issues

**Comment by mattheath** [comment] 2013-05-01 12:42
Going to close this, as not an issue with the PHP module.

**Closed as completed by mattheath** 2013-05-01 12:42 UTC
