### ISSUE TITLE
Creating new project specific pool does not refresh PHP-FPM

### ISSUE THREAD

**Issue by boztek** [mattheath/puppet-php#14] opened 2013-03-20 02:50 UTC
I can happily use either boxen::project and manually declare a project specific pool or use php::project - both with a custom nginx template for some app specifics.

In either case I seem to have to kill php-fpm and rerun boxen for everything to work.

**Comment by mattheath** [comment] 2013-03-20 09:01
Yeah this is similar to #1. It's caused by the `php::fpm::pool` class _requiring_ the `php::fpm` class which includes the service. As the entire class is required, the service can't be notified - it creates a dependency loop.

I think I've worked out a fix which requires changing part of the dependency chain, will have another look later today. For the moment you can use the following to slightly speed this up, rather than having to re-run boxen!

```
boxen --disable-services
boxen --enable-services
```

**Comment by mattheath** [comment] 2013-03-20 22:57
I've merged this, and retagged as `0.4.2`. Pool config files now notify the FPM service for the PHP version, which should trigger a refresh of the service. @boztek could you let me know if it works for you?

**Comment by mattheath** [comment] 2013-05-28 19:24
Closing this as I'm fairly certain it's fixed - let me know if this is still an issue.

**Closed as completed by mattheath** 2013-05-28 19:24 UTC
